spring.application.name=api-gateway

server.port=8080

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cloud.gateway.routes[0].id=booking-service
spring.cloud.gateway.routes[0].uri=lb://2-irctcBooking
spring.cloud.gateway.routes[0].predicates[0]=Path=/irctc/booking/**

spring.cloud.gateway.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=10

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
