spring.application.name=api-gateway

server.port=8011

# =========================
# Eureka
# =========================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# =========================
# Redis
# =========================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# =========================
# Gateway Route
# =========================
spring.cloud.gateway.routes[0].id=booking-service
spring.cloud.gateway.routes[0].uri=lb://2-irctcBooking
spring.cloud.gateway.routes[0].predicates[0]=Path=/irctc/booking/**

# =========================
# Rate Limiter
# =========================
spring.cloud.gateway.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=10

# =========================
# Actuator
# =========================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# IMPORTANT
management.endpoint.gateway.access=read-only

# =========================
# Info
# =========================
info.application.name=IRCTC API Gateway
info.application.description=IRCTC API Gateway with Rate Limiter
info.application.version=1.0.0
