# ==========================================
# APPLICATION
# ==========================================

spring.application.name=api-gateway
server.port=8011


# ==========================================
# EUREKA
# ==========================================

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true


# ==========================================
# REDIS
# ==========================================

spring.data.redis.host=localhost
spring.data.redis.port=6379


# ==========================================
# API GATEWAY ROUTE
# ==========================================

spring.cloud.gateway.routes[0].id=booking-service
spring.cloud.gateway.routes[0].uri=lb://2-irctcBooking
spring.cloud.gateway.routes[0].predicates[0]=Path=/irctc/booking/**


# ==========================================
# ACTUATOR
# ==========================================

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.gateway.access=read-only


# ==========================================
# LOGGING
# ==========================================

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web=DEBUG


# ==========================================
# APPLICATION INFO
# ==========================================

info.application.name=IRCTC API Gateway
info.application.description=IRCTC API Gateway
info.application.version=1.0.0
