server:
  port: 8091

spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE:flipkart_product_db}

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cache:
    type: redis

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
