server.port=8091

spring.application.name=product-service

spring.data.mongodb.uri=mongodb+srv://av70951_db_user:oNEwGF6TGmHJMLyi@cluster0.jpu5ii9.mongodb.net/flipkart_product_db?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=flipkart_product_db

spring.redis.host=${REDIS_HOST:localhost}
spring.redis.port=${REDIS_PORT:6379}

spring.cache.type=redis

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management.endpoints.web.exposure.include=health,info,metrics,prometheus
