server:
  port: 8091

spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb+srv://<av70951_db_user>:oNEwGF6TGmHJMLyi@cluster0.jpu5ii9.mongodb.net/?appName=Cluster0
      database: flipkart_product_db

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

  cache:
    type: redis

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
